name: Build FFmpeg Kit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  VERSION: "6.0.LTS"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install .NET workloads
      run: |
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install maccatalyst
        dotnet workload install macos
        dotnet workload install tvos

    - name: Install dependencies
      run: |
        brew install curl
        brew install unzip

    - name: Clean artifacts
      run: make clean_artifacts

    - name: Download Android JARs
      run: make download_jars

    - name: Download Apple Frameworks
      run: make download_frameworks

    - name: Build Android variants
      run: |
        make build_audio_android
        make build_full_android
        make build_full_gpl_android
        make build_https_android
        make build_https_gpl_android
        make build_min_android
        make build_min_gpl_android
        make build_video_android

    - name: Build Apple variants
      run: |
        make build_audio_apple
        make build_full_apple
        make build_full_gpl_apple
        make build_https_apple
        make build_https_gpl_apple
        make build_min_apple
        make build_min_gpl_apple
        make build_video_apple

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-kit-packages
        path: artifacts/*.nupkg
